"""
network_analysis.py — Social Network Analysis of AOT Influencing Factors
=========================================================================

Constructs a weighted, undirected graph where each node is a financial or
macroeconomic variable and each edge represents the strength of association
between two variables. Supports multiple association measures, configurable
thresholding, community detection, and full network metric computation.

Nodes (9 macroeconomic / market variables)
-------------------------------------------
  AOT Closing Price     — Monthly close of AOT common stock (SET)
  Trading Volume        — Monthly total trading volume of AOT
  SET Index             — Stock Exchange of Thailand benchmark index
  Tourist Arrivals      — International tourist arrivals to Thailand
  Tourism Revenue       — Revenue generated by international tourism
  USD/THB               — USD / Thai Baht exchange rate
  Policy Rate           — Bank of Thailand policy interest rate
  Inflation (CPI)       — Headline Consumer Price Index
  GDP                   — Gross Domestic Product (quarterly → monthly)

Edges (3 association measures)
-------------------------------
  Pearson  r        — Linear correlation coefficient
  Spearman ρ        — Rank-based monotonic correlation
  Mutual Info       — Non-linear dependence (k-NN estimator)

Configurable threshold — edges with |correlation| < threshold are dropped.

Graph Metrics (computed automatically)
---------------------------------------
  Degree Centrality      — Fraction of nodes a given node is connected to.
                           High-degree nodes are directly influencing many
                           other variables in the system.

  Betweenness Centrality — Fraction of shortest paths that pass through a
                           node. High-betweenness nodes act as bridges or
                           gatekeepers in the network.

  Closeness Centrality   — Reciprocal of the sum of shortest-path distances
                           from a node to all others. High-closeness nodes
                           can quickly propagate shocks through the system.

  Eigenvector Centrality — Measures influence based on connections to other
                           high-influence nodes. A node with high eigenvector
                           centrality is connected to nodes that are themselves
                           central (Google's PageRank is a variant).

  PageRank               — Variant of eigenvector centrality with damping.
                           Captures the idea that a node is important if it
                           is linked from other important nodes.

  Community Detection    — Louvain greedy modularity-maximisation algorithm.
                           Groups nodes with denser intra-community edges
                           than inter-community edges. Each node is assigned
                           a community label (0, 1, 2, …).

  Connected Components   — Sets of nodes reachable via any path. In a fully
                           connected graph there is 1 component.

  Network Density        — Ratio of actual edges to possible edges. Ranges
                           from 0 (empty graph) to 1 (complete graph).

  Average Path Length    — Mean shortest-path distance between all node pairs.
                           Shorter average paths imply faster information flow.

  Graph Diameter         — Longest shortest-path distance. Represents the
                           "worst-case" propagation delay in the system.

Visualization (static + interactive)
-------------------------------------
  • Static matplotlib figure with:
      — Node size ∝ Degree Centrality
      — Node colour = Community (qualitative palette)
      — Edge width ∝ |correlation|
      — Edge colour = positive (blue) / negative (red)
  • Publication-quality (300 dpi, SVG export, LaTeX-style fonts)
  • Interactive Plotly figure with:
      — Hover tooltips: node name, community, all 5 centrality values
      — Zoom / pan
      — Search (ctrl+F in browser)
      — Filter by community / centrality range
      — SVG / PNG export via plotly toolbar

Usage
-----
    from aot_stock_network.network_analysis import NetworkBuilder, NetworkAnalyzer, NetworkVisualizer

    builder = NetworkBuilder(df_features)
    G = builder.build_graph(method="pearson", threshold=0.5)

    analyzer = NetworkAnalyzer(G)
    metrics = analyzer.compute_all()
    print(analyzer.summary())

    visualizer = NetworkVisualizer(G, metrics)
    visualizer.plot_static("reports/figures/network_graph.svg")
    visualizer.plot_interactive("reports/figures/network_interactive.html")
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import pandas as pd
from matplotlib import cm as mpl_cm
from matplotlib.colors import Normalize, to_hex
from matplotlib.figure import Figure
from matplotlib.lines import Line2D
from sklearn.feature_selection import mutual_info_regression

logger = logging.getLogger("network")

# ──────────────────────────────────────────────────────────────
# Default node → column mapping
# ──────────────────────────────────────────────────────────────
# Maps canonical node names to likely column patterns in the
# feature DataFrame. Used when the user doesn't supply an
# explicit mapping.
DEFAULT_COLUMN_PATTERNS: Dict[str, List[str]] = {
    "AOT Close": ["aot_close", "aot_closing_price"],
    "Trading Volume": ["aot_volume", "trading_volume"],
    "SET Index": ["set_close", "set_index", "set_close_price"],
    "Tourist Arrivals": [
        "tourists_total_arrivals",
        "tourist_arrivals",
        "tourists_arrivals",
        "international_tourists",
    ],
    "Tourism Revenue": ["tourism_revenue", "tourist_revenue", "tourism_income"],
    "USD/THB": ["fx_usdthb_rate", "usdthb", "fx_rate", "exch_usdthb"],
    "Policy Rate": ["policy_policy_rate", "policy_rate", "interest_rate"],
    "Inflation": ["cpi_cpi_headline", "cpi_headline", "inflation_cpi", "cpi"],
    "GDP": ["gdp_gdp", "gdp", "gdp_value"],
}

# Qualitative colour palette for communities (up to 20)
COMMUNITY_COLORS = [
    "#4C72B0",
    "#DD8452",
    "#55A868",
    "#C44E52",
    "#8172B3",
    "#937860",
    "#DA8BC3",
    "#8C8C8C",
    "#CCB974",
    "#64B5CD",
    "#E47A6A",
    "#7BAF7A",
    "#B279A0",
    "#AF8F60",
    "#5D9B9B",
    "#D4A6C8",
    "#98A8C8",
    "#C8A872",
    "#A0A0A0",
    "#B8C8A0",
]

PUBLICATION_COLORS: Dict[str, str] = {
    "positive": "#2E7D32",
    "negative": "#C62828",
    "neutral": "#757575",
    "edge_pos": "#1E88E5",
    "edge_neg": "#E53935",
    "bg": "#FAFAFA",
    "text": "#212121",
}


# ══════════════════════════════════════════════════════════════
# Helper functions
# ══════════════════════════════════════════════════════════════


def _resolve_columns(
    df: pd.DataFrame,
    column_mapping: Optional[Dict[str, str]] = None,
) -> Dict[str, str]:
    """Map canonical node names to actual DataFrame columns.

    Parameters
    ----------
    df : pd.DataFrame
        Feature dataset.
    column_mapping : dict, optional
        Explicit {node_name: column_name} mapping.

    Returns
    -------
    dict
        {node_name: column_name} for all successfully resolved nodes.
    """
    if column_mapping:
        resolved = {}
        for node, col in column_mapping.items():
            if col in df.columns:
                resolved[node] = col
            else:
                logger.warning("Column '%s' for node '%s' not found", col, node)
        return resolved

    resolved: Dict[str, str] = {}
    for node, patterns in DEFAULT_COLUMN_PATTERNS.items():
        for pat in patterns:
            if pat in df.columns:
                resolved[node] = pat
                break
    return resolved


def _compute_mutual_information_matrix(
    df: pd.DataFrame,
    columns: List[str],
    random_state: int = 42,
) -> pd.DataFrame:
    """Compute pairwise Mutual Information matrix (k-NN estimator)."""
    n = len(columns)
    mi_mat = np.zeros((n, n))
    arr = df[columns].dropna().values.astype(np.float64)
    for i in range(n):
        X = np.delete(arr, i, axis=1)
        y = arr[:, i]
        mi = mutual_info_regression(X, y, random_state=random_state)
        mi_mat[i, :i] = mi[:i]
        mi_mat[:i, i] = mi[:i]
    return pd.DataFrame(mi_mat, index=columns, columns=columns)


def _rescale(values: np.ndarray, target_min: float = 0.5, target_max: float = 1.0) -> np.ndarray:
    """Min-max rescale to [target_min, target_max]; constant input → target_max."""
    lo, hi = values.min(), values.max()
    if np.isclose(lo, hi):
        return np.full_like(values, target_max)
    return target_min + (values - lo) / (hi - lo) * (target_max - target_min)


# ══════════════════════════════════════════════════════════════
# 1. NetworkBuilder
# ══════════════════════════════════════════════════════════════


class NetworkBuilder:
    """Construct a weighted undirected graph from a feature DataFrame.

    Parameters
    ----------
    df : pd.DataFrame
        Feature dataset with time index.
    column_mapping : dict, optional
        {node_name: column_name} mapping. Auto-resolved if None.
    """

    def __init__(
        self,
        df: pd.DataFrame,
        column_mapping: Optional[Dict[str, str]] = None,
    ):
        self._df = df.copy()
        self._node_map = _resolve_columns(df, column_mapping)
        self._graph: Optional[nx.Graph] = None
        self._edge_method: Optional[str] = None
        self._edge_threshold: Optional[float] = None

        logger.info(
            "NetworkBuilder initialized | %d nodes resolved | columns=%s",
            len(self._node_map),
            list(self._node_map.keys()),
        )

    # ── public properties ─────────────────────────────────—

    @property
    def nodes(self) -> List[str]:
        """List of resolved node names."""
        return list(self._node_map.keys())

    @property
    def graph(self) -> Optional[nx.Graph]:
        """Built graph (None before :meth:`build_graph`)."""
        return self._graph

    # ── build_graph ─────────────────────────────────────────

    def build_graph(
        self,
        method: str = "pearson",
        threshold: float = 0.3,
        min_edges: int = 1,
        absolute_value: bool = True,
    ) -> nx.Graph:
        """Build the association graph.

        Parameters
        ----------
        method : {"pearson", "spearman", "mutual_info"}
            Association measure for edge weights.
        threshold : float
            Edges with |weight| < threshold are dropped.
        min_edges : int
            Ensure every node has at least this many edges (iteratively
            lowers threshold within bounds).
        absolute_value : bool
            If True, edges with *negative* Pearson/Spearman are kept
            (weight taken as abs value). Only meaningful for pearson/spearman.

        Returns
        -------
        nx.Graph
            Weighted undirected graph.
        """
        nodes = self.nodes
        if len(nodes) < 2:
            raise ValueError(f"Need ≥2 nodes, got {len(nodes)}")

        columns = [self._node_map[n] for n in nodes]
        data = self._df[columns].dropna()
        logger.info(
            "build_graph: method=%s threshold=%.2f data=%d rows", method, threshold, len(data)
        )

        # ── compute weight matrix ──────────────────────────
        if method == "pearson":
            weight_df = data.corr(method="pearson")
        elif method == "spearman":
            weight_df = data.corr(method="spearman")
        elif method == "mutual_info":
            weight_df = _compute_mutual_information_matrix(data, columns)
        else:
            raise ValueError(
                f"Unknown method '{method}'. Use 'pearson', 'spearman', or 'mutual_info'."
            )

        # Rename to node names
        weight_df.index = nodes
        weight_df.columns = nodes

        # ── threshold ──────────────────────────────────────
        G = nx.Graph()
        G.add_nodes_from(nodes)

        current_threshold = threshold
        for _ in range(20):  # safety limit
            G.clear_edges()
            for i, u in enumerate(nodes):
                for j, v in enumerate(nodes):
                    if j <= i:
                        continue
                    w = weight_df.loc[u, v]
                    use_weight = abs(w) if absolute_value and method != "mutual_info" else w
                    if use_weight >= current_threshold:
                        G.add_edge(u, v, weight=use_weight, raw_weight=w, method=method)

            # Check min_edges
            if min_edges and G.number_of_nodes() > 0:
                min_deg = min(d for _, d in G.degree())
                if min_deg >= min_edges or current_threshold <= 0.05:
                    break
                current_threshold = max(current_threshold * 0.75, 0.0)
                logger.debug(
                    "Lowering threshold to %.3f (min degree=%d)", current_threshold, min_deg
                )
            else:
                break

        self._graph = G
        self._edge_method = method
        self._edge_threshold = current_threshold

        logger.info(
            "build_graph done | %d nodes %d edges | density=%.4f | threshold=%.3f",
            G.number_of_nodes(),
            G.number_of_edges(),
            nx.density(G),
            current_threshold,
        )
        return G

    # ── adjacency matrix ───────────────────────────────────

    def adjacency_matrix(self) -> pd.DataFrame:
        """Return the weighted adjacency matrix as a DataFrame."""
        if self._graph is None:
            raise RuntimeError("Call build_graph() first.")
        return nx.to_pandas_adjacency(self._graph, weight="weight")

    def correlation_matrix(self) -> pd.DataFrame:
        """Return the full correlation/association matrix."""
        if self._graph is None:
            raise RuntimeError("Call build_graph() first.")
        nodes = self.nodes
        columns = [self._node_map[n] for n in nodes]
        data = self._df[columns].dropna()
        method = self._edge_method or "pearson"
        if method == "pearson":
            return data.corr(method="pearson")
        elif method == "spearman":
            return data.corr(method="spearman")
        else:
            return _compute_mutual_information_matrix(data, columns)

    def summary(self) -> str:
        """Text summary of the built network."""
        if self._graph is None:
            return "No graph built yet."
        lines = [
            "NetworkBuilder Summary",
            "======================",
            f"Nodes: {self._graph.number_of_nodes()}",
            f"Edges: {self._graph.number_of_edges()}",
            f"Density: {nx.density(self._graph):.4f}",
            f"Method: {self._edge_method}",
            f"Threshold: {self._edge_threshold:.3f}",
            f"Nodes: {', '.join(self.nodes)}",
        ]
        return "\n".join(lines)


# ══════════════════════════════════════════════════════════════
# 2. NetworkAnalyzer
# ══════════════════════════════════════════════════════════════


@dataclass
class NetworkMetrics:
    """Container for all computed graph metrics."""

    degree_centrality: Dict[str, float] = field(default_factory=dict)
    betweenness_centrality: Dict[str, float] = field(default_factory=dict)
    closeness_centrality: Dict[str, float] = field(default_factory=dict)
    eigenvector_centrality: Dict[str, float] = field(default_factory=dict)
    pagerank: Dict[str, float] = field(default_factory=dict)
    community: Dict[str, int] = field(default_factory=dict)
    n_communities: int = 0
    connected_components: int = 1
    network_density: float = 0.0
    average_path_length: Optional[float] = None
    diameter: Optional[int] = None

    def to_dataframe(self) -> pd.DataFrame:
        """Return metrics as a DataFrame (rows = nodes)."""
        nodes = sorted(self.degree_centrality.keys())
        rows = []
        for n in nodes:
            rows.append(
                {
                    "node": n,
                    "degree_centrality": self.degree_centrality.get(n, 0.0),
                    "betweenness_centrality": self.betweenness_centrality.get(n, 0.0),
                    "closeness_centrality": self.closeness_centrality.get(n, 0.0),
                    "eigenvector_centrality": self.eigenvector_centrality.get(n, 0.0),
                    "pagerank": self.pagerank.get(n, 0.0),
                    "community": self.community.get(n, -1),
                }
            )
        return pd.DataFrame(rows).set_index("node")


class NetworkAnalyzer:
    """Compute all graph-theoretic metrics on a NetworkX graph.

    Parameters
    ----------
    G : nx.Graph
        Weighted undirected graph built by NetworkBuilder.
    """

    def __init__(self, G: nx.Graph):
        self._G = G
        self._metrics: Optional[NetworkMetrics] = None

    # ── compute_all ────────────────────────────────────────

    def compute_all(self) -> NetworkMetrics:
        """Compute every metric in one pass.

        Returns
        -------
        NetworkMetrics
            Dataclass with all centrality, community, and global metrics.
        """
        G = self._G
        m = NetworkMetrics()

        n_nodes = G.number_of_nodes()

        # ── Centralities ───────────────────────────────────
        if n_nodes >= 2:
            m.degree_centrality = nx.degree_centrality(G)
            m.betweenness_centrality = nx.betweenness_centrality(
                G,
                weight="weight",
                normalized=True,
            )
            try:
                m.closeness_centrality = nx.closeness_centrality(
                    G,
                    distance="weight",
                )
            except Exception:
                m.closeness_centrality = {n: 0.0 for n in G.nodes()}

            try:
                m.eigenvector_centrality = nx.eigenvector_centrality(
                    G,
                    weight="weight",
                    max_iter=1000,
                    tol=1e-6,
                )
            except Exception:
                m.eigenvector_centrality = {n: 0.0 for n in G.nodes()}

            m.pagerank = nx.pagerank(G, weight="weight")
        else:
            for n in G.nodes():
                v = 1.0 if n_nodes == 1 else 0.0
                m.degree_centrality[n] = v
                m.betweenness_centrality[n] = 0.0
                m.closeness_centrality[n] = v
                m.eigenvector_centrality[n] = v
                m.pagerank[n] = v

        # ── Community Detection (Louvain) ──────────────────
        try:
            comm_map_raw = nx.community.louvain_communities(G, weight="weight", seed=42)
            m.community = {}
            for cid, members in enumerate(comm_map_raw):
                for node in members:
                    m.community[node] = cid
            m.n_communities = len(set(m.community.values()))
        except Exception as exc:
            logger.warning("Community detection failed: %s", exc)
            m.community = {n: 0 for n in G.nodes()}
            m.n_communities = 1

        # ── Connected Components ───────────────────────────
        m.connected_components = nx.number_connected_components(G)

        # ── Global metrics ─────────────────────────────────
        m.network_density = nx.density(G)

        if n_nodes >= 2 and nx.is_connected(G):
            try:
                m.average_path_length = nx.average_shortest_path_length(G, weight="weight")
            except Exception:
                m.average_path_length = None
            try:
                m.diameter = nx.diameter(G, weight="weight")
            except Exception:
                m.diameter = None
        else:
            m.average_path_length = None
            m.diameter = None

        self._metrics = m
        logger.info(
            "NetworkAnalyzer: %d centralities | %d communities | density=%.4f | components=%d",
            n_nodes,
            m.n_communities,
            m.network_density,
            m.connected_components,
        )
        return m

    @property
    def metrics(self) -> Optional[NetworkMetrics]:
        """Last computed metrics."""
        return self._metrics

    def summary(self) -> str:
        """Text summary of all metrics."""
        m = self._metrics
        if m is None:
            return "No metrics computed yet. Call compute_all()."

        lines = [
            "NetworkAnalysis Summary",
            "=======================",
            f"Nodes: {len(m.degree_centrality)}",
            f"Edges: {self._G.number_of_edges()}",
            f"Network Density: {m.network_density:.4f}",
            "",
            "Centrality (top node by each metric):",
        ]
        for label, cent in [
            ("Degree", m.degree_centrality),
            ("Betweenness", m.betweenness_centrality),
            ("Closeness", m.closeness_centrality),
            ("Eigenvector", m.eigenvector_centrality),
            ("PageRank", m.pagerank),
        ]:
            if cent:
                top = max(cent, key=cent.get)
                lines.append(f"  {label:15s} -> {top} ({cent[top]:.4f})")
            else:
                lines.append(f"  {label:15s} -> (empty)")

        lines.append("")
        lines.append(f"Communities: {m.n_communities}")
        if m.community:
            comm_groups: Dict[int, List[str]] = {}
            for node, cid in m.community.items():
                comm_groups.setdefault(cid, []).append(node)
            for cid in sorted(comm_groups):
                lines.append(f"  Community {cid}: {', '.join(comm_groups[cid])}")

        lines.append("")
        lines.append(f"Connected Components: {m.connected_components}")
        lines.append(f"Average Path Length:  {m.average_path_length or 'N/A (disconnected)'}")
        lines.append(f"Graph Diameter:       {m.diameter or 'N/A (disconnected)'}")

        return "\n".join(lines)


# ══════════════════════════════════════════════════════════════
# 3. NetworkVisualizer
# ══════════════════════════════════════════════════════════════


class NetworkVisualizer:
    """Static (matplotlib) and interactive (Plotly) network visualisation.

    Parameters
    ----------
    G : nx.Graph
        Weighted graph.
    metrics : NetworkMetrics
        Pre-computed metrics from NetworkAnalyzer.
    layout : str, default "spring"
        Layout algorithm: "spring", "circular", "kamada_kawai", "shell",
        "spectral", or a precomputed dict.
    seed : int, default 42
        Random seed for reproducible layouts.
    """

    def __init__(
        self,
        G: nx.Graph,
        metrics: NetworkMetrics,
        layout: Union[str, Dict[str, Tuple[float, float]]] = "spring",
        seed: int = 42,
    ):
        self._G = G
        self._metrics = metrics
        self._pos = self._compute_layout(layout, seed)

    # ── layout ─────────────────────────────────────────────

    def _compute_layout(
        self,
        layout: Union[str, Dict[str, Tuple[float, float]]],
        seed: int,
    ) -> Dict[str, np.ndarray]:
        """Compute or return node positions."""
        if isinstance(layout, dict):
            return layout
        if layout == "spring":
            return nx.spring_layout(self._G, k=1.5, iterations=100, seed=seed)
        elif layout == "circular":
            return nx.circular_layout(self._G)
        elif layout == "kamada_kawai":
            return nx.kamada_kawai_layout(self._G, weight="weight")
        elif layout == "shell":
            return nx.shell_layout(self._G)
        elif layout == "spectral":
            return nx.spectral_layout(self._G, weight="weight")
        else:
            logger.warning("Unknown layout '%s', falling back to spring", layout)
            return nx.spring_layout(self._G, seed=seed)

    # ── node / edge attribute accessors ────────────────────

    def _node_communities(self) -> Dict[str, int]:
        return self._metrics.community

    def _node_degree(self) -> Dict[str, int]:
        return dict(self._G.degree())

    def _node_sizes(self, min_size: int = 600, max_size: int = 2500) -> List[float]:
        deg = np.array([d for _, d in self._G.degree()])
        return list(_rescale(deg, min_size, max_size))

    def _node_colors(self) -> List[str]:
        comm = self._node_communities()
        n_comm = max(comm.values()) + 1 if comm else 1
        palette = COMMUNITY_COLORS[:n_comm]
        return [palette[comm.get(n, 0) % len(palette)] for n in self._G.nodes()]

    def _edge_widths(self, min_w: float = 0.5, max_w: float = 5.0) -> List[float]:
        ws = [abs(d.get("weight", 0.5)) for _, _, d in self._G.edges(data=True)]
        return list(_rescale(np.array(ws), min_w, max_w))

    def _edge_colors(self) -> List[str]:
        colors = []
        for _, _, d in self._G.edges(data=True):
            raw = d.get("raw_weight", d.get("weight", 0))
            if raw >= 0:
                colors.append(PUBLICATION_COLORS["edge_pos"])
            else:
                colors.append(PUBLICATION_COLORS["edge_neg"])
        return colors

    def _edge_alphas(self) -> List[float]:
        return [
            min(abs(d.get("weight", 0.5)) * 0.5 + 0.2, 1.0) for _, _, d in self._G.edges(data=True)
        ]

    # ── Static matplotlib plot ─────────────────────────────

    def plot_static(
        self,
        output_path: Optional[Union[str, Path]] = None,
        figsize: Tuple[float, float] = (14, 10),
        dpi: int = 300,
        title: str = "Social Network Graph of AOT Influencing Factors",
        show_labels: bool = True,
        show_colorbar: bool = True,
    ) -> Tuple[Figure, plt.Axes]:
        """Publication-quality static network visualisation.

        Parameters
        ----------
        output_path : str or Path, optional
            If given, save figure to this path (SVG strongly recommended).
        figsize : tuple, default (14, 10)
        dpi : int, default 300
        title : str
        show_labels : bool, default True
        show_colorbar : bool, default True

        Returns
        -------
        (fig, ax) tuple.
        """
        G = self._G
        node_sizes = self._node_sizes()
        node_colors = self._node_colors()
        edge_widths = self._edge_widths()
        edge_cols = self._edge_colors()
        edge_alphas = self._edge_alphas()

        fig, ax = plt.subplots(figsize=figsize, facecolor="white")
        ax.set_facecolor("white")

        # ── edges ──────────────────────────────────────────
        for (u, v, d), w, ec, ea in zip(
            G.edges(data=True),
            edge_widths,
            edge_cols,
            edge_alphas,
        ):
            x0, y0 = self._pos[u]
            x1, y1 = self._pos[v]
            ax.plot(
                [x0, x1],
                [y0, y1],
                linewidth=w,
                color=ec,
                alpha=ea,
                solid_capstyle="round",
                zorder=1,
            )

        # ── nodes ──────────────────────────────────────────
        xs = [self._pos[n][0] for n in G.nodes()]
        ys = [self._pos[n][1] for n in G.nodes()]
        nodes_plot = ax.scatter(
            xs,
            ys,
            s=node_sizes,
            c=node_colors,
            edgecolors="white",
            linewidth=1.5,
            zorder=2,
            alpha=0.9,
        )

        # ── labels ─────────────────────────────────────────
        if show_labels:
            for node in G.nodes():
                x, y = self._pos[node]
                deg = G.degree(node)
                ax.annotate(
                    f"{node}\n(deg={deg})",
                    (x, y),
                    textcoords="offset points",
                    xytext=(0, 12),
                    fontsize=9,
                    fontweight="bold",
                    ha="center",
                    va="bottom",
                    color=PUBLICATION_COLORS["text"],
                    bbox=dict(
                        boxstyle="round,pad=0.3",
                        facecolor="white",
                        edgecolor="none",
                        alpha=0.85,
                    ),
                    zorder=3,
                )

        # ── legend (node size → degree) ───────────────────
        deg_values = sorted(set(d for _, d in G.degree()))
        if len(deg_values) > 5:
            deg_values = [
                min(deg_values),
                deg_values[len(deg_values) // 3],
                deg_values[2 * len(deg_values) // 3],
                max(deg_values),
            ]
        legend_elements = [
            Line2D(
                [0],
                [0],
                marker="o",
                color="w",
                markerfacecolor=PUBLICATION_COLORS["neutral"],
                markersize=np.sqrt(s / np.pi) * 0.4,
                label=f"deg={d}",
            )
            for s, d in zip(
                _rescale(np.array([float(d) for d in deg_values]), 600, 2500),
                deg_values,
            )
        ]
        legend_elements += [
            Line2D(
                [0],
                [0],
                color=PUBLICATION_COLORS["edge_pos"],
                linewidth=3,
                alpha=0.6,
                label="Positive Correlation",
            ),
            Line2D(
                [0],
                [0],
                color=PUBLICATION_COLORS["edge_neg"],
                linewidth=3,
                alpha=0.6,
                label="Negative Correlation",
            ),
        ]
        ax.legend(
            handles=legend_elements,
            loc="upper left",
            frameon=True,
            fontsize=8,
            title="Node Size ∝ Degree",
            title_fontsize=9,
            ncol=1,
        )

        # ── colour bar (community) ────────────────────────
        if show_colorbar and self._metrics.n_communities > 1:
            cmap = mpl_cm.colors.ListedColormap(COMMUNITY_COLORS[: self._metrics.n_communities])
            norm = Normalize(vmin=0, vmax=self._metrics.n_communities - 1)
            sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
            sm.set_array([])
            cbar = fig.colorbar(
                sm, ax=ax, ticks=range(self._metrics.n_communities), shrink=0.6, pad=0.02
            )
            cbar.set_label("Community", fontsize=10)
            cbar.ax.tick_params(labelsize=8)

        # ── styling ────────────────────────────────────────
        ax.set_title(title, fontweight="bold", fontsize=14, pad=16)
        ax.axis("off")
        fig.tight_layout(pad=1.5)

        # ── export ─────────────────────────────────────────
        if output_path:
            p = Path(output_path)
            p.parent.mkdir(parents=True, exist_ok=True)
            fig.savefig(p, dpi=dpi, bbox_inches="tight", facecolor="white")
            logger.info("Exported static network graph: %s", p)

        return fig, ax

    # ── centrality heatmap ─────────────────────────────────

    def plot_centrality_heatmap(
        self,
        output_path: Optional[Union[str, Path]] = None,
        figsize: Tuple[float, float] = (10, 6),
    ) -> Tuple[Figure, plt.Axes]:
        """Heatmap of all centrality metrics across nodes.

        Parameters
        ----------
        output_path : str or Path, optional
        figsize : tuple, default (10, 6)

        Returns
        -------
        (fig, ax) tuple.
        """
        df_metrics = self._metrics.to_dataframe()
        cent_cols = [
            "degree_centrality",
            "betweenness_centrality",
            "closeness_centrality",
            "eigenvector_centrality",
            "pagerank",
        ]
        data = df_metrics[cent_cols]

        fig, ax = plt.subplots(figsize=figsize)
        im = ax.imshow(data.values, cmap="YlOrRd", aspect="auto", vmin=0, vmax=1)

        # Labels
        ax.set_xticks(range(len(cent_cols)))
        ax.set_xticklabels([c.replace("_", "\n").title() for c in cent_cols], fontsize=9)
        ax.set_yticks(range(len(data.index)))
        ax.set_yticklabels(data.index, fontsize=9)

        # Annotate cells
        for i in range(data.shape[0]):
            for j in range(data.shape[1]):
                val = data.iloc[i, j]
                color = "white" if val > 0.6 else "black"
                ax.text(
                    j,
                    i,
                    f"{val:.2f}",
                    ha="center",
                    va="center",
                    fontsize=8,
                    color=color,
                    fontweight="bold",
                )

        ax.set_title("Centrality Metrics Across Nodes", fontweight="bold", pad=12)
        fig.colorbar(im, ax=ax, shrink=0.8, label="Centrality Score")
        fig.tight_layout()

        if output_path:
            p = Path(output_path)
            p.parent.mkdir(parents=True, exist_ok=True)
            fig.savefig(p, dpi=300, bbox_inches="tight")
            logger.info("Exported centrality heatmap: %s", p)

        return fig, ax

    # ── centrality bar chart ───────────────────────────────

    def plot_centrality_barchart(
        self,
        output_path: Optional[Union[str, Path]] = None,
        figsize: Tuple[float, float] = (12, 7),
    ) -> Tuple[Figure, plt.Axes]:
        """Grouped bar chart comparing centrality metrics per node.

        Parameters
        ----------
        output_path : str or Path, optional
        figsize : tuple, default (12, 7)

        Returns
        -------
        (fig, ax) tuple.
        """
        df_metrics = self._metrics.to_dataframe()
        cent_cols = [
            "degree_centrality",
            "betweenness_centrality",
            "closeness_centrality",
            "eigenvector_centrality",
            "pagerank",
        ]
        data = df_metrics[cent_cols]

        x = np.arange(len(data))
        n_metrics = len(cent_cols)
        width = 0.8 / n_metrics
        colors = ["#4C72B0", "#DD8452", "#55A868", "#C44E52", "#8172B3"]

        fig, ax = plt.subplots(figsize=figsize)
        for j, (col, color) in enumerate(zip(cent_cols, colors)):
            ax.bar(
                x + j * width,
                data[col].values,
                width,
                label=col.replace("_", " ").title(),
                color=color,
                edgecolor="white",
                linewidth=0.5,
            )

        ax.set_xticks(x + width * (n_metrics - 1) / 2)
        ax.set_xticklabels(data.index, fontsize=10, rotation=30, ha="right")
        ax.set_ylabel("Centrality Score", fontsize=11)
        ax.set_title("Centrality Metrics Comparison", fontweight="bold", pad=12)
        ax.legend(fontsize=8, frameon=True)
        ax.set_ylim(0, 1.05)
        ax.grid(axis="y", alpha=0.3)
        fig.tight_layout()

        if output_path:
            p = Path(output_path)
            p.parent.mkdir(parents=True, exist_ok=True)
            fig.savefig(p, dpi=300, bbox_inches="tight")
            logger.info("Exported centrality barchart: %s", p)

        return fig, ax

    # ── degree distribution ────────────────────────────────

    def plot_degree_distribution(
        self,
        output_path: Optional[Union[str, Path]] = None,
        figsize: Tuple[float, float] = (8, 5),
    ) -> Tuple[Figure, plt.Axes]:
        """Histogram of node degrees.

        Parameters
        ----------
        output_path : str or Path, optional
        figsize : tuple, default (8, 5)

        Returns
        -------
        (fig, ax) tuple.
        """
        degrees = [d for _, d in self._G.degree()]
        fig, ax = plt.subplots(figsize=figsize)
        ax.hist(
            degrees,
            bins=min(len(degrees), 10),
            color="#4C72B0",
            edgecolor="white",
            linewidth=1.2,
            alpha=0.8,
        )
        ax.set_xlabel("Degree", fontsize=11)
        ax.set_ylabel("Frequency", fontsize=11)
        ax.set_title("Degree Distribution", fontweight="bold", pad=12)
        ax.grid(axis="y", alpha=0.3)

        mean_deg = np.mean(degrees)
        ax.axvline(
            mean_deg,
            color="#C44E52",
            linestyle="--",
            linewidth=1.5,
            alpha=0.8,
            label=f"Mean={mean_deg:.1f}",
        )
        ax.legend(fontsize=9)
        fig.tight_layout()

        if output_path:
            p = Path(output_path)
            p.parent.mkdir(parents=True, exist_ok=True)
            fig.savefig(p, dpi=300, bbox_inches="tight")
            logger.info("Exported degree distribution: %s", p)

        return fig, ax

    # ── adjacency heatmap ──────────────────────────────────

    def plot_adjacency_heatmap(
        self,
        df_adj: pd.DataFrame,
        output_path: Optional[Union[str, Path]] = None,
        figsize: Tuple[float, float] = (9, 8),
    ) -> Tuple[Figure, plt.Axes]:
        """Heatmap of the weighted adjacency matrix.

        Parameters
        ----------
        df_adj : pd.DataFrame
            Adjacency matrix from NetworkBuilder.adjacency_matrix().
        output_path : str or Path, optional
        figsize : tuple, default (9, 8)

        Returns
        -------
        (fig, ax) tuple.
        """
        fig, ax = plt.subplots(figsize=figsize)
        im = ax.imshow(df_adj.values, cmap="RdYlBu_r", aspect="equal", vmin=-1, vmax=1)

        ax.set_xticks(range(len(df_adj.columns)))
        ax.set_xticklabels(df_adj.columns, fontsize=9, rotation=45, ha="right")
        ax.set_yticks(range(len(df_adj.index)))
        ax.set_yticklabels(df_adj.index, fontsize=9)

        for i in range(df_adj.shape[0]):
            for j in range(df_adj.shape[1]):
                val = df_adj.iloc[i, j]
                if val != 0:
                    color = "white" if abs(val) > 0.6 else "black"
                    ax.text(j, i, f"{val:.2f}", ha="center", va="center", fontsize=7, color=color)

        ax.set_title("Weighted Adjacency Matrix", fontweight="bold", pad=12)
        fig.colorbar(im, ax=ax, shrink=0.8, label="Edge Weight")
        fig.tight_layout()

        if output_path:
            p = Path(output_path)
            p.parent.mkdir(parents=True, exist_ok=True)
            fig.savefig(p, dpi=300, bbox_inches="tight")
            logger.info("Exported adjacency heatmap: %s", p)

        return fig, ax

    # ── Interactive Plotly graph ───────────────────────────

    def plot_interactive(
        self,
        output_path: Optional[Union[str, Path]] = None,
        title: str = "AOT Influencing Factors — Social Network Graph",
    ) -> "Figure":  # noqa: F821
        """Interactive Plotly network graph with hover, zoom, and filter.

        Features
        --------
        • Hover:  node name, community, all 5 centrality values
        • Zoom:   scroll to zoom, click-drag to pan
        • Search: browser Ctrl+F works on text labels
        • Filter: use plotly legend to toggle communities on/off
        • Export: plotly toolbar (camera icon → SVG / PNG)

        Parameters
        ----------
        output_path : str or Path, optional
            HTML file path for the interactive graph.
        title : str, default "AOT Influencing Factors — Social Network Graph"

        Returns
        -------
        plotly.graph_objects.Figure
        """
        import plotly.graph_objects as go

        G = self._G
        m = self._metrics
        edge_x: List[Optional[float]] = []
        edge_y: List[Optional[float]] = []
        edge_colors_plotly: List[str] = []
        edge_widths_plotly: List[float] = []

        for u, v, d in G.edges(data=True):
            x0, y0 = self._pos[u]
            x1, y1 = self._pos[v]
            edge_x += [x0, x1, None]
            edge_y += [y0, y1, None]
            raw = d.get("raw_weight", d.get("weight", 0.5))
            edge_colors_plotly.append(
                to_hex(PUBLICATION_COLORS["edge_pos"])
                if raw >= 0
                else to_hex(PUBLICATION_COLORS["edge_neg"])
            )
            edge_widths_plotly.append(abs(d.get("weight", 0.5)) * 3 + 0.5)

        # Edge traces per colour (positive / negative) for legend
        pos_edge_x: List[Optional[float]] = []
        pos_edge_y: List[Optional[float]] = []
        neg_edge_x: List[Optional[float]] = []
        neg_edge_y: List[Optional[float]] = []

        for u, v, d in G.edges(data=True):
            x0, y0 = self._pos[u]
            x1, y1 = self._pos[v]
            raw = d.get("raw_weight", d.get("weight", 0.5))
            pts = [x0, x1, None]
            if raw >= 0:
                pos_edge_x += pts
                pos_edge_y += [y0, y1, None]
            else:
                neg_edge_x += pts
                neg_edge_y += [y0, y1, None]

        edge_traces = []
        if pos_edge_x:
            edge_traces.append(
                go.Scatter(
                    x=pos_edge_x,
                    y=pos_edge_y,
                    mode="lines",
                    line=dict(color=to_hex(PUBLICATION_COLORS["edge_pos"]), width=1),
                    hoverinfo="none",
                    showlegend=True,
                    name="Positive Correlation",
                )
            )
        if neg_edge_x:
            edge_traces.append(
                go.Scatter(
                    x=neg_edge_x,
                    y=neg_edge_y,
                    mode="lines",
                    line=dict(color=to_hex(PUBLICATION_COLORS["edge_neg"]), width=1),
                    hoverinfo="none",
                    showlegend=True,
                    name="Negative Correlation",
                )
            )

        # Node trace
        node_x: List[float] = []
        node_y: List[float] = []
        node_text: List[str] = []
        node_sizes_plotly: List[float] = []
        node_colors_plotly: List[str] = []
        node_communities_list: List[int] = []
        community_labels: List[str] = []

        sizes = self._node_sizes(min_size=15, max_size=50)
        colors = self._node_colors()

        for i, node in enumerate(G.nodes()):
            x, y = self._pos[node]
            node_x.append(x)
            node_y.append(y)
            node_sizes_plotly.append(sizes[i])
            node_colors_plotly.append(colors[i])

            cid = m.community.get(node, -1)
            node_communities_list.append(cid)
            community_labels.append(f"Community {cid}")

            deg_c = f"{m.degree_centrality.get(node, 0):.4f}"
            bet_c = f"{m.betweenness_centrality.get(node, 0):.4f}"
            clo_c = f"{m.closeness_centrality.get(node, 0):.4f}"
            eig_c = f"{m.eigenvector_centrality.get(node, 0):.4f}"
            pr_c = f"{m.pagerank.get(node, 0):.4f}"

            node_text.append(
                f"<b>{node}</b><br>"
                f"Community: {cid}<br>"
                f"Degree: {deg_c}<br>"
                f"Betweenness: {bet_c}<br>"
                f"Closeness: {clo_c}<br>"
                f"Eigenvector: {eig_c}<br>"
                f"PageRank: {pr_c}"
            )

        node_trace = go.Scatter(
            x=node_x,
            y=node_y,
            mode="markers+text",
            text=[n for n in G.nodes()],
            textposition="top center",
            textfont=dict(size=10, color="#212121"),
            marker=dict(
                size=node_sizes_plotly,
                color=node_colors_plotly,
                line=dict(color="white", width=1.5),
            ),
            hoverinfo="text",
            hovertext=node_text,
            showlegend=False,
            customdata=node_communities_list,
        )

        # Legend for communities
        community_traces = []
        unique_comm = sorted(set(community_labels))
        comm_color_map = {
            f"Community {i}": colors[i % len(colors)] for i in range(max(node_communities_list) + 1)
        }
        for cl in unique_comm:
            cid = int(cl.split()[-1])
            community_traces.append(
                go.Scatter(
                    x=[None],
                    y=[None],
                    mode="markers",
                    marker=dict(size=10, color=comm_color_map.get(cl, "#888")),
                    showlegend=True,
                    name=cl,
                    legendgroup=cl,
                )
            )

        data = edge_traces + [node_trace] + community_traces

        fig = go.Figure(data=data)
        fig.update_layout(
            title=dict(text=title, font=dict(size=16)),
            showlegend=True,
            hovermode="closest",
            legend=dict(
                title="Legend",
                font=dict(size=10),
                itemsizing="constant",
                groupclick="toggleitem",
            ),
            xaxis=dict(visible=False, showgrid=False, zeroline=False),
            yaxis=dict(visible=False, showgrid=False, zeroline=False),
            plot_bgcolor="white",
            paper_bgcolor="white",
            margin=dict(l=20, r=20, t=60, b=20),
            dragmode="pan",
        )

        # ── export HTML ────────────────────────────────────
        if output_path:
            p = Path(output_path)
            p.parent.mkdir(parents=True, exist_ok=True)
            fig.write_html(
                p,
                include_plotlyjs="cdn",
                config={
                    "scrollZoom": True,
                    "displayModeBar": True,
                    "modeBarButtonsToAdd": ["drawline", "eraseshape"],
                    "toImageButtonOptions": {
                        "format": "svg",
                        "filename": p.stem,
                        "height": 800,
                        "width": 1200,
                    },
                },
            )
            logger.info("Exported interactive graph: %s", p)

        return fig

    # ── export GraphML ─────────────────────────────────────

    def export_graphml(self, output_path: Union[str, Path]) -> Path:
        """Export graph in GraphML format for Gephi / Cytoscape.

        Node attributes: degree, all 5 centralities, community.
        Edge attributes: weight, raw_weight, method.

        Parameters
        ----------
        output_path : str or Path

        Returns
        -------
        Path
            Saved file path.
        """
        p = Path(output_path)
        p.parent.mkdir(parents=True, exist_ok=True)

        G = self._G.copy()
        m = self._metrics

        # Attach node attributes
        for node in G.nodes():
            G.nodes[node]["degree"] = G.degree(node)
            G.nodes[node]["degree_centrality"] = m.degree_centrality.get(node, 0.0)
            G.nodes[node]["betweenness_centrality"] = m.betweenness_centrality.get(node, 0.0)
            G.nodes[node]["closeness_centrality"] = m.closeness_centrality.get(node, 0.0)
            G.nodes[node]["eigenvector_centrality"] = m.eigenvector_centrality.get(node, 0.0)
            G.nodes[node]["pagerank"] = m.pagerank.get(node, 0.0)
            G.nodes[node]["community"] = m.community.get(node, -1)

        nx.write_graphml(G, str(p))
        logger.info("Exported GraphML: %s", p)
        return p

    # ── generate_all ───────────────────────────────────────

    def generate_all(
        self,
        output_dir: Union[str, Path],
        df_adj: Optional[pd.DataFrame] = None,
        prefix: str = "",
    ) -> Dict[str, Path]:
        """Generate all figures and exports in one call.

        Parameters
        ----------
        output_dir : str or Path
        df_adj : pd.DataFrame, optional
            Adjacency matrix (for heatmap). Obtained from
            :meth:`NetworkBuilder.adjacency_matrix()`.
        prefix : str, optional
            File name prefix.

        Returns
        -------
        dict
            {description: Path} mapping.
        """
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        paths: Dict[str, Path] = {}

        n_expected = 5  # static plots
        if df_adj is not None:
            n_expected += 1

        def _plot_and_save(fn, name: str, *args, **kwargs):
            try:
                result = fn(*args, **kwargs)
                if isinstance(result, tuple):
                    fig = result[0]
                else:
                    fig = result
                path = out / f"{name}.svg"
                fig.savefig(path, dpi=300, bbox_inches="tight")
                plt.close(fig)
                paths[name] = path
            except Exception as exc:
                logger.error("Failed to generate '%s': %s", name, exc)

        _plot_and_save(self.plot_static, f"{prefix}network_graph")
        _plot_and_save(self.plot_centrality_heatmap, f"{prefix}centrality_heatmap")
        _plot_and_save(self.plot_centrality_barchart, f"{prefix}centrality_barchart")
        _plot_and_save(self.plot_degree_distribution, f"{prefix}degree_distribution")
        if df_adj is not None:
            _plot_and_save(self.plot_adjacency_heatmap, f"{prefix}adjacency_heatmap", df_adj)

        # Interactive HTML
        try:
            html_path = out / f"{prefix}network_interactive.html"
            self.plot_interactive(html_path)
            paths[f"{prefix}network_interactive"] = html_path
        except Exception as exc:
            logger.error("Failed to generate interactive: %s", exc)

        # GraphML
        try:
            gml_path = out / f"{prefix}network.graphml"
            self.export_graphml(gml_path)
            paths[f"{prefix}network_graphml"] = gml_path
        except Exception as exc:
            logger.error("Failed to export GraphML: %s", exc)

        logger.info("Generated %d/%d exports in %s", len(paths), n_expected + 2, out)
        return paths


# ══════════════════════════════════════════════════════════════
# Convenience function: full pipeline
# ══════════════════════════════════════════════════════════════


def run_network_pipeline(
    df: pd.DataFrame,
    column_mapping: Optional[Dict[str, str]] = None,
    method: str = "pearson",
    threshold: float = 0.3,
    output_dir: Union[str, Path] = "reports/figures",
    generate_exports: bool = True,
) -> Dict[str, Any]:
    """Run the full network analysis pipeline in one call.

    Parameters
    ----------
    df : pd.DataFrame
        Feature dataset.
    column_mapping : dict, optional
        {node_name: column_name}.
    method : str, default "pearson"
        Association measure.
    threshold : float, default 0.3
        Edge weight threshold.
    output_dir : str or Path, default "reports/figures"
        Export directory.
    generate_exports : bool, default True
        If True, generate all figures and exports.

    Returns
    -------
    dict with keys "builder", "analyzer", "visualizer", "metrics", "paths".
    """
    builder = NetworkBuilder(df, column_mapping)
    G = builder.build_graph(method=method, threshold=threshold)

    analyzer = NetworkAnalyzer(G)
    metrics = analyzer.compute_all()

    visualizer = NetworkVisualizer(G, metrics)
    paths: Dict[str, Path] = {}
    if generate_exports:
        paths = visualizer.generate_all(output_dir, df_adj=builder.adjacency_matrix())

    return {
        "builder": builder,
        "analyzer": analyzer,
        "visualizer": visualizer,
        "metrics": metrics,
        "paths": paths,
    }


# ══════════════════════════════════════════════════════════════
# Module exports
# ══════════════════════════════════════════════════════════════

__all__ = [
    "NetworkBuilder",
    "NetworkAnalyzer",
    "NetworkMetrics",
    "NetworkVisualizer",
    "run_network_pipeline",
    "DEFAULT_COLUMN_PATTERNS",
    "COMMUNITY_COLORS",
]
